update main.text
caccs/Manual-do-Bixo pull request #12
Opened 2018-01-20 01:49 UTC by beasabreu

atualização dos preços dos ônibus, lugares na seção de alimentação e bares, falei dos materiais disponíveis no grupo geral da bcc na subseção das listas
(talvez eu tenha feito caca no latex? talvez. perdoa porque não mexo nisso desde o primeiro semestre)

2018-01-20 03:19 UTC, eiguike commented
Oi Beatriz!

Apesar de não estar mais presente por aí na universidade acabei recebendo a notificação de PR deste repositório, hahaha, valeu pela contribuição! :smile: 

Compilei aqui o projeto junto com o seu commit, entretanto, acredito que as partes das descrições dos lugares acabou quebrando o estilo e também os textos daquela seção. 

[manual.pdf](https://github.com/caccs/Manual-do-Bixo/files/1648478/manual.pdf)

Se você quiser manter as modificações, iria pedir para mudar o estilo do texto, no caso, de duas colunas para uma e também colocar uma breve descrição nos lugares restantes.

O que acha?

2018-01-22 12:09 UTC, Darkkgreen commented
Aonde exatamente quebrou, @eiguike ? A parte dos médicos?

2018-01-22 12:41 UTC, Jostavo requested changes
Tem uns problemas na parte de comida (quebraram algumas coisas). Não creio que seja necessário uma descrição (caso fique quebrado a página por causa dos textinhos ahahaha. @giovana-morais o que você acha?
Acho interessante pular uma linha também nos horários (Domingo tá ficando sempre na mesma linha), talvez fique ergonomicamente melhor.

2018-01-22 12:42 UTC, Darkkgreen commented
Se preferir, eu posso forçar o Merge e fixar os problemas

2018-01-22 14:37 UTC, eiguike commented
Se você for mergear e depois arrumar, recomendo você criar uma branch apropriada e fazer o merge para essa nova branch. Posteriormente você iria modificar e fazer o pullrequest para a master.

2018-01-23 23:46 UTC, giovana-morais commented
eu acho que transformar a seção de comidas pra uma coluna só não compensa pq é só um tipo rápido de informação. o ideal é suprimir as descrições mesmo. esse commit da @beasabreu provavelmente vai dar conflito com o do @Cremonildo pq ele mexeu nessa parte dos ônibus e etc.

2018-01-23 23:49 UTC, giovana-morais requested changes

2018-01-23 23:49 UTC, giovana-morais commented on vida_academica/main.tex
> +      \newline Provavelmente o mais discado quando alguém decide ir de lanches. Tem promoção de 2 lanches por R\$ 15 às terças-feiras e pizza por R\$ 10 reais às quartas e quintas. (Cuidado com o col
`\newline Provavelmente o mais discado quando alguém decide ir de lanches. Tem promoção de 2 lanches por R\$ 15 às terças-feiras e pizza por R\$ 10 reais às quartas e quintas. (Cuidado com o colesterol!!)`

acho que em vez de deixar isso na descrição (ou seja, dentro do itemize), dá pra deixar num Brotip depois dos nomes e endereços dos outros estabelecimentos.

2018-01-23 23:49 UTC, giovana-morais commented on vida_academica/main.tex
> +      \newline Esfihas muito, muito gostosas num preço bom.
`\newline Esfihas muito, muito gostosas num preço bom.`

esse aqui pode arrancar mesmo

2018-09-12 20:05 UTC, Darkkgreen commented
Seguimos no aguardo

2018-10-30 12:52 UTC, closed without merging