mudanças do issue de adaptação
caccs/Manual-do-Bixo pull request #15
Opened 2018-01-22 20:11 UTC by Cremonildo

adicionado

- horário de serviço do técnico
- infos sobre a cantina
- falar do grupo geral de BCC
    - mencionar as listas que rolam, os materiais de estudo etc
- telefone da secretaria + e-mail da secretária

2018-01-22 22:14 UTC, eiguike commented
Eaí @Cremonildo,

seu commit acabou quebrando a imagem dos "primeiros semestres", ou no caso, você acabou não commitando ela. Poderia verificar isso?

2018-01-22 22:18 UTC, Cremonildo commented
Eu havia esquecido de commitar a imagem, kkkkk, mas agora já está commitada

2018-01-22 22:30 UTC, eiguike commented
Hmm, tenho péssimas notícias.

A imagem que você pegou está com uma resolução bem baixa e acredito que durante a impressão possa dar algum problema de leitura.

Sugestão: tentar refazer o fluxograma lá das matérias por um programa parecido com o Inkscape, ou tentar extrair somente a página do .pdf (não tirando screenshot ou algo parecido);

Se não der certo, acredito que o melhor seja dar um revert neste commit e tentar conversar com a Profa. Yeda para ver se ela poderia repassar o fluxograma num formato em que possamos editar.

2018-01-22 23:33 UTC, Cremonildo commented
Vou pedir praYeda se ela possui em uma resolução melhor. Porque aquele foi retirado do pdf e está ruim mesmo lá

2018-01-23 12:04 UTC, Darkkgreen commented
Conversa com ela, quando commitar a gente verifica e faz o merge procê

2018-01-23 12:25 UTC, Darkkgreen commented on introducao_curso/main.tex
> +Na UFSCar utilizamos o sistema de créditos - você pode entender créditos como horas semanais de um semestre - em que, no curso Ciência da Computação você precisará de 217 créditos para se formar send
> você precisará de 217 créditos para se formar sendo elas

"você precisará de 217 créditos para se formar, sendo eles:"

2018-01-23 12:26 UTC, Darkkgreen commented on introducao_curso/main.tex
> +O IRA é o Índice de Rendimento Acadêmico e é adotado para classificação na concorrência de prioridade de inscrição de disciplinas, transferências internas e bolsas para iniciação científica
Ponto final necessário

2018-01-23 12:36 UTC, Darkkgreen commented on vida_academica/main.tex
> +\subsubsection{Links De compras/vendas/trocas}
E Esse Camel Case Aí?

2018-01-23 12:36 UTC, Darkkgreen commented on vida_academica/main.tex
> +    \item \texttt{Compra e Venda Móveis} \texttt{<https://www.facebook.com/groups/192993804175207>}
CamelCaseOnceAgain

2018-01-23 12:37 UTC, Darkkgreen commented on vida_academica/main.tex
> +O responsável por abrir e cuidar desses laboratórios é o nosso técnico Tiago, porém caso seja necessário o Centro Acadêmico tem a permissão de abrir os laboratórios para estudos, o horário de serviço
rsrsrsrs

2018-01-23 12:37 UTC, Darkkgreen commented on vida_academica/main.tex
> +ou baixe o app do cardápio do Ru feito pela Beets Jr (disponível apenas para Android)
RU

2018-01-23 12:40 UTC, Darkkgreen commented on vida_academica/main.tex
> +Cada curso da UFSCar tem uma secretaria, ela é responsável por mandar e-mails de estágios, avisos de professores, informações da faculdade em geral e entregas de documentos são geralmente entregues a
>Cada curso da UFSCar tem uma secretaria,

"possui" deixaria mais formalzinho

>por mandar e-mails de estágios

"por enviar e-mails sobre estágios"

>informações da faculdade em geral e entregas de documentos são geralmente entregues a ela

"informações da faculdade em geral. Entregas de documentos são feitas para ela" algo em torno disso

2018-01-23 12:43 UTC, Darkkgreen commented on vida_academica/main.tex
> +Até ano passado nós tínhamos a cantinas que vendia salgados, almoço e bebidas em geral, porém no ano de 2017 por problemas contratuais ela fechou, enquanto não temos uma cantina, temos alunos e pesso
>Até ano passado nós tínhamos a cantinas que vendia salgados, almoço e bebidas em geral, porém no ano de 2017 por problemas contratuais ela fechou, enquanto não temos uma cantina, temos alunos e pessoas de fora que vendem diferentes tipos de comida e bebidas, até mesmo comidas veganas.

"Até 2017 a UFSCar possuía uma cantina fixa. Porém, no meio do ano, a mesma acabou fechando por problemas de contrato. Com a saída da cantina, alunos e pessoas de fora passaram a vender diferentes tipos de comidas e bebidas (incluindo comidas veganas!!) dentro da faculdade." ou algo em torno disso

2018-01-23 12:45 UTC, Darkkgreen commented on vida_academica/main.tex
> +O seviço de xerox e cópias fica localizado próximo ao prédio do RU, na área de vivência, o funcionamento acontece de segunda a sexta e o expediente é das 8h às 21h.
>O seviço de xerox

Tá faltando o **r** em serviço

>na área de vivência, o funcionamento acontece

"na área de vivência. O funcionamento acontece"

2018-01-23 12:47 UTC, Darkkgreen commented on vida_academica/main.tex
> +Recomendamos a participação no grupo geral da computação no facebook, lá estão praticamente todos os alunos e ex-alunos do curso, rolam discussões sobre as matérias, docs colaborativos e todos se aju
>facebook

Facebook, afinal é um nome

>listas e provas, portanto quando tiverem a

"listas e provas. Portanto, quando tiverem a oportunidade, peçam"

2018-01-23 12:48 UTC, Jostavo requested changes
Interessante realizar as correções que comentei. Também gostaria de ressaltar que você consegue linkar uma Issue a esse PR.

2018-01-23 16:54 UTC, closed without merging

2018-01-23 16:58 UTC, Cremonildo commented on vida_academica/main.tex
> +    \item \texttt{Compra e Venda Móveis} \texttt{<https://www.facebook.com/groups/192993804175207>}
Aqui é um Camel Case devido a ser o nome do grupo no Facebook, mas posso deixar normal se acha que fica melhor

2018-01-23 17:07 UTC, slasho17 commented on vida_academica/main.tex
> +    \item \texttt{Compra e Venda Móveis} \texttt{<https://www.facebook.com/groups/192993804175207>}
\item \ texttt{VENDAS BARGANHAS EM SOROCABA.}\texttt{<https://www.facebook.com/groups/barganha/about/>}

um grupo de venda bem grandinho até, o nome é assim mesmo, com o ponto final junto, mas pode mudar se achar melhor

\item \texttt{LARICÃO UFSCar Sorocaba} \texttt{<https://www.facebook.com/groups/148134829245871/?ref=br_rs>}

novamente, o nome do grupo é em maiusculo

2018-01-23 17:12 UTC, slasho17 commented on vida_academica/main.tex
> +O seviço de xerox e cópias fica localizado próximo ao prédio do RU, na área de vivência, o funcionamento acontece de segunda a sexta e o expediente é das 8h às 21h.
seria bom adicionar o email deles
UFSCar.xerox@gmail.com

2018-01-23 17:15 UTC, Darkkgreen commented on vida_academica/main.tex
> +    \item \texttt{Compra e Venda Móveis} \texttt{<https://www.facebook.com/groups/192993804175207>}
Acredito que compensa mais normalizar mesmo pra não poluir muito o documento

2018-01-23 17:18 UTC, Darkkgreen commented on vida_academica/main.tex
> +O seviço de xerox e cópias fica localizado próximo ao prédio do RU, na área de vivência, o funcionamento acontece de segunda a sexta e o expediente é das 8h às 21h.
Já tá adicionado. O que você tá vendo aqui são só as mudanças, e não o texto completo

2018-01-23 17:32 UTC, Cremonildo commented on vida_academica/main.tex
> +    \item \texttt{Compra e Venda Móveis} \texttt{<https://www.facebook.com/groups/192993804175207>}
Normalizei os nomes no próximo commit, só deixei UFSCar e Sorocaba maiúsculo por serem nomes próprios