Update de informações
caccs/Manual-do-Bixo pull request #20
Opened 2018-10-30 12:51 UTC by Darkkgreen

Algumas modificações feitas pela Xipinha em outro PR mas que ficaram pendentes. Adicionei algumas coisas e pretendo deixar o PR aberto pra gente ir adicionando algumas informações novas, pra manter atualizado.

2018-10-30 13:55 UTC, eiguike commented on vida_academica/main.tex
> +    \item \textbf{Shopping Cidade (dead inside)}
Não sei se esse dead inside ficaria bacana huauhahuahua.

2018-10-30 13:55 UTC, eiguike commented on vida_academica/main.tex
> +    \item \textbf{Red Bar}
Sagrado lugar.

2018-10-30 13:57 UTC, eiguike commented
Você poderia utilizar o cherry-pick para selecionar os commits da xipinha, poderia ser feito algo assim:

git cherry-pick <commit-hash>

2018-10-30 13:57 UTC, eiguike approved these changes

2018-10-30 14:28 UTC, giovana-morais commented on vida_academica/main.tex
> +            É um bom lugar para ter várias horas de sono e maximizar a economia do dinheiro. O preço varia de R\$600 a R\$800 (depende do proprietário/imobiliária e localização), com o condomínio inc
eu acho que em vez de 
> você poderia dividir o espaço com cerca de 3 pessoas"

podemos deixar como 
> você pode dividir o espaço com cerca de 3 pessoas 

:thinking:

2018-10-30 14:31 UTC, giovana-morais commented on vida_academica/main.tex
> +Como última opção, temos a moradia da UFSCar, entretanto, deixamos na seção Bolsas da UFSCar que se encontra na página \pageref{moradia}.
acho qeu aqui dá pra mudar pra 
"""
Como última opção, existe a moradia da UFSCar. Os detalhes estão descritos na página \pageref{moradia}
"""

2018-10-30 14:35 UTC, giovana-morais commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
EXISTE UFSCAR DE DOMINGO AGORA!!!!!!!11 :tada:  

é necessário confirmar os horários. acredito que o pessoal do CA tenha que pesquisar direitinho. vou deixar isso aqui pro @vinixxyama pq não tenho a @ da Xipinha.

2018-10-30 14:42 UTC, giovana-morais requested changes
deixei anotado algumas coisinhas que eu acho que precisam mudar (na vdd, a única coisa que precisa *mesmo* é o lance do ônibus de domingo, mas ainda tem tempo até os bixos do ano que vem entrarem)

2018-10-30 14:43 UTC, giovana-morais commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
ah é, agora tem o interbairros tbm. precisa ver quando que ele tá rodando e por onde ele passa.

2018-10-30 14:56 UTC, Darkkgreen commented on vida_academica/main.tex
> +    \item \textbf{Shopping Cidade (dead inside)}
Coloquei na brincadeira, mas era mais pra questionar se devemos deixar ele se tá morto o shopping

2018-10-30 14:56 UTC, Darkkgreen commented on vida_academica/main.tex
> +            É um bom lugar para ter várias horas de sono e maximizar a economia do dinheiro. O preço varia de R\$600 a R\$800 (depende do proprietário/imobiliária e localização), com o condomínio inc
Posso mudar, é suave

2018-10-30 14:58 UTC, Darkkgreen commented
Não sabia que eu consegui dar cherry-pick em um commit de um fork, mas bom saber. Vamos utilizando esse PR pra ir melhorando e adicionando informações, vou procurar mais tarde sobre o ônibus pra tentar explicar e realizar as modificações que vcs apontaram

2018-10-30 15:01 UTC, Jostavo commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
@beasabreu

2018-10-30 17:47 UTC, eiguike commented on vida_academica/main.tex
> +    \item \textbf{Shopping Cidade (dead inside)}
shopping morto vc fala o plaza então né? ambos são da itavuvu.

2018-10-31 11:43 UTC, Darkkgreen commented on vida_academica/main.tex
> +    \item \textbf{Shopping Cidade (dead inside)}
Damn então acho que confundi

2018-10-31 13:09 UTC, Darkkgreen commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
Funciona aos feriados?

2018-10-31 13:36 UTC, giovana-morais commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
Gabriel disse que não

2018-10-31 14:41 UTC, Darkkgreen commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
Beleza, vou reescrever o texto then

2018-10-31 15:07 UTC, beasabreu commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
peraí, vou olhar no site da urbes

2018-11-01 11:52 UTC, giovana-morais reviewed
só arrumar o negócio do ônibus de domingo e já era :ship:

2018-11-01 12:29 UTC, Darkkgreen commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
Vai avisando

2019-01-08 10:45 UTC, Darkkgreen commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
Still no aguardo

2019-01-08 11:36 UTC, giovana-morais commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
deixa os caras, josta, cê já tá formado ahahaha 💟

2019-01-08 19:04 UTC, Darkkgreen commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
Ai que rude, só queria ajudar

2019-01-10 21:50 UTC, giovana-morais commented on vida_academica/main.tex
> +\textbf{LEMBRE-SE QUE}: A linha da UFSCar não roda aos domingos e feriados! Então se você decidir morar perto da universidade e quiser passear, vai ter que usar o Piracema. Os passes de estudante do
é brinks, jostinha ❤️

2019-01-11 13:26 UTC, eiguike commented
Atualizei a branch com as últimas atualizações da `master`.

2019-01-15 11:35 UTC, eiguike commented
☝️

2019-05-15 01:56 UTC, closed without merging