Updates pra 2019
caccs/Manual-do-Bixo pull request #21
Opened 2019-01-10 13:47 UTC by Vinality

Atualizado emails da secretaria; Arrumados alguns links; Informações sobre a cantina do roxo

2019-01-10 13:55 UTC, Jostavo requested changes

2019-01-10 13:55 UTC, Darkkgreen commented on vida_academica/main.tex
> +  \newlina alunosbccs@ufscar.br (Este é o email geral de BCC. Tome cuidado ao enviar algo para esse endereço pois será automaticamente repassado à todos os alunos do curso. Não faça igual o Brinquedo
'newlina' pra 'newline'

2019-01-10 13:55 UTC, Darkkgreen commented on vida_academica/main.tex
> +Na entrada do prédio roxo, atualmente encontra-se uma vendinha regular com salgados, café de diferentes sabores, bolos e docinhos gerais.
'Atualmente, na entrada do prédio roxo, existe uma vendinha regular...' acho q ficaria melhor, but dunno

2019-01-10 15:56 UTC, eiguike requested changes

2019-01-10 15:56 UTC, eiguike commented on vida_academica/main.tex
> +  \newline mcastilho@ufscar.br
Ficaria estranho deixar todos os e-mails na mesma linha? Poderia verificar isso?

2019-01-10 15:56 UTC, eiguike commented on vida_academica/main.tex
> +  \newlina alunosbccs@ufscar.br (Este é o email geral de BCC. Tome cuidado ao enviar algo para esse endereço pois será automaticamente repassado à todos os alunos do curso. Não faça igual o Brinquedo
Não sei se é legal mencionar o nome do amiguinho mas acho válido esse aviso.

2019-01-10 15:56 UTC, eiguike commented on vida_academica/main.tex
> +  \newlina alunosbccs@ufscar.br (Este é o email geral de BCC. Tome cuidado ao enviar algo para esse endereço pois será automaticamente repassado à todos os alunos do curso. Não faça igual o Brinquedo
Se ficar bacana deixar todos os e-mails na mesma linha, acredito que o aviso pode ser utilizado como `\newline`.

2019-01-10 16:35 UTC, Darkkgreen commented on vida_academica/main.tex
> +  \newlina alunosbccs@ufscar.br (Este é o email geral de BCC. Tome cuidado ao enviar algo para esse endereço pois será automaticamente repassado à todos os alunos do curso. Não faça igual o Brinquedo
Fica meio estranho mesmo o aviso junto

2019-01-10 21:41 UTC, giovana-morais commented on vida_academica/main.tex
> +  \newlina alunosbccs@ufscar.br (Este é o email geral de BCC. Tome cuidado ao enviar algo para esse endereço pois será automaticamente repassado à todos os alunos do curso. Não faça igual o Brinquedo
tira o nome do Brinquedo mesmo, não fica legal. acho que o aviso pode ser mudado pra
acho tbm que ficaria legal deixar "todos os alunos do curso" em negrito pra dar aquela assustada.

2019-01-10 21:45 UTC, giovana-morais requested changes
as mudanças de texto são bem básicas, de resto tá mt bão. :shipit:

2019-01-10 21:45 UTC, giovana-morais commented on vida_academica/main.tex
>  Até 2017 a UFSCar possuía uma cantina fixa. Porém, no meio do ano, a mesma acabou fechando por problemas de contrato. Com a saída da cantina, alunos e pessoas de fora passaram a vender diferentes tip
muda isso aqui pra 
"Até 2017 a UFSCar possuía uma cantina fixa**, porém**, no meio do ano, fechou por problemas de contrato." 
acho que é bom evitar frases curtíssimas, ainda mais quando é uma oração que tem a ver com a outra.  🤓 
outra coisa (a última desse parágrafo, juro): eu acho que dá pra trocar "pessoas de fora" por "não-alunos" ou algo similar. mas, assim, isso foi só um incômodo meu. você pode avaliar se realmente faz sentido ou não. 👍

2019-01-11 00:24 UTC, eiguike commented
Uma outra coisa que notei @Vinality, mude a branch de destino para master se possível.

2019-01-11 12:54 UTC, Darkkgreen commented
> Uma outra coisa que notei @Vinality, mude a branch de destino para master se possível.

Realmente, @Vinality só editar o PR e modificar o destino pra master do CACCS, senão a gente terá que realizar dois merges

2019-01-11 15:59 UTC, Vinality commented
> Uma outra coisa que notei @Vinality, mude a branch de destino para master se possível.

Foi feito. Perdão pelos erros. Sou meio leigo com esses repos colaborativos ainda. My bad

2019-01-11 16:08 UTC, Vinality commented on vida_academica/main.tex
> +  \newline mcastilho@ufscar.br
Eu achei que fica melhor pois quebra melhor a página e n fica nada pra pagina seguinte.
![screenshot 2019-01-11 14 07 09](https://user-images.githubusercontent.com/26964388/51045234-40f60780-15aa-11e9-98d1-11d6c4f6426c.png)

2019-01-11 18:37 UTC, eiguike commented
Você se baseou numa branch que o @Darkkgreen estava trabalhando, faça esses passos:

```sh
git reset HEAD~5
git checkout .
git cherry-pick 6e9c869be2e19eb783442ec3c5e9dfd6d476f323
git cherry-pick 469b92a78f6e630a540143741244cbc40b3975d2
git push origin fix/update-infos-late-2018 -f
``` 
Esses comandos irão resetar o estado da sua branch atual para a versão que estava naquele momento, e posteriormente inserir seus commits nela e pushar forçadamente na sua branch.

Acredito que você tenha que mergear com a master depois, mas isso da para ser resolvido por aqui.

2019-01-12 19:29 UTC, giovana-morais approved these changes
por mim agora tá tudo tranquilex, manda bala 🚢

2019-01-23 00:37 UTC, eiguike approved these changes

2019-05-15 01:53 UTC, Jostavo approved these changes

2019-05-15 01:53 UTC, merged